package mapping

func InitEntities() {
Entities[1]   = EntityEntry{TRName: "Blue Slime", MCName: "minecraft:slime"}
Entities[2]   = EntityEntry{TRName: "Green Slime", MCName: "minecraft:slime"}
Entities[3]   = EntityEntry{TRName: "Green Slime", MCName: "minecraft:slime"}
Entities[4]   = EntityEntry{TRName: "Pinky", MCName: "minecraft:slime"}
Entities[5]   = EntityEntry{TRName: "Baby Slime", MCName: "minecraft:slime"}
Entities[6]   = EntityEntry{TRName: "Zombie", MCName: "minecraft:zombie"}
Entities[7]   = EntityEntry{TRName: "Demon Eye", MCName: "minecraft:phantom"}
Entities[8]   = EntityEntry{TRName: "Angry Bones", MCName: "minecraft:skeleton"}
Entities[9]   = EntityEntry{TRName: "Big Boned", MCName: "minecraft:skeleton"}
Entities[10]  = EntityEntry{TRName: "Short Bones", MCName: "minecraft:skeleton"}
Entities[11]  = EntityEntry{TRName: "Cursed Skull", MCName: "minecraft:wither_skeleton"}
Entities[12]  = EntityEntry{TRName: "Dungeon Slime", MCName: "minecraft:slime"}
Entities[13]  = EntityEntry{TRName: "Eater of Souls", MCName: "minecraft:vex"}
Entities[14]  = EntityEntry{TRName: "Giant Worm", MCName: "minecraft:silverfish"}
Entities[15]  = EntityEntry{TRName: "Devourer", MCName: "minecraft:silverfish"}
Entities[16]  = EntityEntry{TRName: "Mother Slime", MCName: "minecraft:slime"}
Entities[17]  = EntityEntry{TRName: "Cave Bat", MCName: "minecraft:bat"}
Entities[18]  = EntityEntry{TRName: "Jungle Bat", MCName: "minecraft:bat"}
Entities[19]  = EntityEntry{TRName: "Ice Bat", MCName: "minecraft:bat"}
Entities[20]  = EntityEntry{TRName: "Lava Bat", MCName: "minecraft:bat"}
Entities[21]  = EntityEntry{TRName: "Skeleton", MCName: "minecraft:skeleton"}
Entities[22]  = EntityEntry{TRName: "Piranha", MCName: "minecraft:pufferfish"}
Entities[23]  = EntityEntry{TRName: "Vulture", MCName: "minecraft:phantom"}
Entities[24]  = EntityEntry{TRName: "Harpy", MCName: "minecraft:parrot"}
Entities[25]  = EntityEntry{TRName: "Antlion", MCName: "minecraft:spider"}
Entities[26]  = EntityEntry{TRName: "Skeleton", MCName: "minecraft:skeleton"}
Entities[27]  = EntityEntry{TRName: "Hornet", MCName: "minecraft:bee"}
Entities[28]  = EntityEntry{TRName: "Man Eater", MCName: "minecraft:vine"}
Entities[29]  = EntityEntry{TRName: "Undead Miner", MCName: "minecraft:zombie"}
Entities[30]  = EntityEntry{TRName: "Tim", MCName: "minecraft:wizard"}
Entities[31]  = EntityEntry{TRName: "Dark Caster", MCName: "minecraft:witch"}
Entities[32]  = EntityEntry{TRName: "Fire Imp", MCName: "minecraft:blaze"}
Entities[33]  = EntityEntry{TRName: "Goblin Scout", MCName: "minecraft:pillager"}
Entities[34]  = EntityEntry{TRName: "Cave Bat", MCName: "minecraft:bat"}
Entities[35]  = EntityEntry{TRName: "King Slime", MCName: "minecraft:slime"}
Entities[36]  = EntityEntry{TRName: "Jungle Slime", MCName: "minecraft:slime"}
Entities[37]  = EntityEntry{TRName: "Vulture", MCName: "minecraft:phantom"}
Entities[38]  = EntityEntry{TRName: "Meteor Head", MCName: "minecraft:blaze"}
Entities[39]  = EntityEntry{TRName: "Chaos Elemental", MCName: "minecraft:enderman"}
Entities[40]  = EntityEntry{TRName: "Slimer", MCName: "minecraft:slime"}
Entities[41]  = EntityEntry{TRName: "Gastropod", MCName: "minecraft:shulker"}
Entities[42]  = EntityEntry{TRName: "Wyvern", MCName: "minecraft:ender_dragon"}
Entities[43]  = EntityEntry{TRName: "Piranha", MCName: "minecraft:pufferfish"}
Entities[44]  = EntityEntry{TRName: "Angler Fish", MCName: "minecraft:pufferfish"}
Entities[45]  = EntityEntry{TRName: "Shark", MCName: "minecraft:dolphin"}
Entities[46]  = EntityEntry{TRName: "Crab", MCName: "minecraft:turtle"}
Entities[47]  = EntityEntry{TRName: "Wall Creeper", MCName: "minecraft:cave_spider"}
Entities[48]  = EntityEntry{TRName: "Black Recluse", MCName: "minecraft:spider"}
Entities[49]  = EntityEntry{TRName: "Unicorn", MCName: "minecraft:horse"}
Entities[50]  = EntityEntry{TRName: "Queen Bee", MCName: "minecraft:bee"}
Entities[51]  = EntityEntry{TRName: "Mimic", MCName: "minecraft:chest_minecart"}
Entities[52]  = EntityEntry{TRName: "Corrupt Mimic", MCName: "minecraft:chest_minecart"}
Entities[53]  = EntityEntry{TRName: "Hallowed Mimic", MCName: "minecraft:chest_minecart"}
Entities[54]  = EntityEntry{TRName: "Wraith", MCName: "minecraft:ghast"}
Entities[55]  = EntityEntry{TRName: "Wall of Flesh", MCName: "minecraft:wither"}
Entities[56]  = EntityEntry{TRName: "The Hungry", MCName: "minecraft:zombie"}
Entities[57]  = EntityEntry{TRName: "Leech", MCName: "minecraft:silverfish"}
Entities[58]  = EntityEntry{TRName: "Wandering Eye", MCName: "minecraft:phantom"}
Entities[59]  = EntityEntry{TRName: "Lava Slime", MCName: "minecraft:magma_cube"}
Entities[60]  = EntityEntry{TRName: "Hellbat", MCName: "minecraft:bat"}
Entities[61]  = EntityEntry{TRName: "Demon", MCName: "minecraft:blaze"}
Entities[62]  = EntityEntry{TRName: "Voodoo Demon", MCName: "minecraft:blaze"}
Entities[63]  = EntityEntry{TRName: "Bone Serpent", MCName: "minecraft:silverfish"}
Entities[64]  = EntityEntry{TRName: "Spiked Slime", MCName: "minecraft:slime"}
Entities[65]  = EntityEntry{TRName: "Ice Slime", MCName: "minecraft:slime"}
Entities[66]  = EntityEntry{TRName: "Spiked Ice Slime", MCName: "minecraft:slime"}
Entities[67]  = EntityEntry{TRName: "Toxic Sludge", MCName: "minecraft:slime"}
Entities[68]  = EntityEntry{TRName: "Flying Fish", MCName: "minecraft:cod"}
Entities[69]  = EntityEntry{TRName: "Umbrella Slime", MCName: "minecraft:slime"}
Entities[70]  = EntityEntry{TRName: "Raincoat Zombie", MCName: "minecraft:zombie"}
Entities[71]  = EntityEntry{TRName: "Angry Nimbus", MCName: "minecraft:ghast"}
Entities[72]  = EntityEntry{TRName: "Eye of Cthulhu", MCName: "minecraft:wither_skeleton"}
Entities[73]  = EntityEntry{TRName: "Servant of Cthulhu", MCName: "minecraft:vex"}
Entities[74]  = EntityEntry{TRName: "Eater of Worlds", MCName: "minecraft:silverfish"}
Entities[75]  = EntityEntry{TRName: "Meteor Head", MCName: "minecraft:blaze"}
Entities[76]  = EntityEntry{TRName: "Goblin Sorcerer", MCName: "minecraft:witch"}
Entities[77]  = EntityEntry{TRName: "Goblin Thief", MCName: "minecraft:pillager"}
Entities[78]  = EntityEntry{TRName: "Goblin Warrior", MCName: "minecraft:vindicator"}
Entities[79]  = EntityEntry{TRName: "Goblin Archer", MCName: "minecraft:pillager"}
Entities[80]  = EntityEntry{TRName: "Skeletron", MCName: "minecraft:wither_skeleton"}
Entities[81]  = EntityEntry{TRName: "Skeletron Hand", MCName: "minecraft:skeleton"}
Entities[82]  = EntityEntry{TRName: "Deerclops", MCName: "minecraft:ravager"}
Entities[83]  = EntityEntry{TRName: "Brain of Cthulhu", MCName: "minecraft:wither"}
Entities[84]  = EntityEntry{TRName: "Creeper", MCName: "minecraft:creeper"}
Entities[85]  = EntityEntry{TRName: "Ichor Sticker", MCName: "minecraft:slime"}
Entities[86]  = EntityEntry{TRName: "Clinger", MCName: "minecraft:slime"}
Entities[87]  = EntityEntry{TRName: "World Feeder", MCName: "minecraft:silverfish"}
Entities[88]  = EntityEntry{TRName: "Moss Hornet", MCName: "minecraft:bee"}
Entities[89]  = EntityEntry{TRName: "Mothron", MCName: "minecraft:phantom"}
Entities[90]  = EntityEntry{TRName: "Mothron Egg", MCName: "minecraft:egg"}
Entities[91]  = EntityEntry{TRName: "Mothron Larva", MCName: "minecraft:silverfish"}
Entities[92]  = EntityEntry{TRName: "Granite Golem", MCName: "minecraft:iron_golem"}
Entities[93]  = EntityEntry{TRName: "Granite Elemental", MCName: "minecraft:blaze"}
Entities[94]  = EntityEntry{TRName: "Hoplite", MCName: "minecraft:skeleton"}
Entities[95]  = EntityEntry{TRName: "Medusa", MCName: "minecraft:witch"}
Entities[96]  = EntityEntry{TRName: "Pigron", MCName: "minecraft:piglin"}
Entities[97]  = EntityEntry{TRName: "Ice Golem", MCName: "minecraft:iron_golem"}
Entities[98]  = EntityEntry{TRName: "Wolf", MCName: "minecraft:wolf"}
Entities[99]  = EntityEntry{TRName: "Ice Elemental", MCName: "minecraft:blaze"}
Entities[100] = EntityEntry{TRName: "Sand Slime", MCName: "minecraft:slime"}
Entities[101] = EntityEntry{TRName: "Mummy", MCName: "minecraft:husk"}
Entities[102] = EntityEntry{TRName: "Dune Splicer", MCName: "minecraft:silverfish"}
Entities[103] = EntityEntry{TRName: "Pixie", MCName: "minecraft:allay"}
Entities[104] = EntityEntry{TRName: "Unicorn", MCName: "minecraft:horse"}
Entities[105] = EntityEntry{TRName: "Armored Viking", MCName: "minecraft:skeleton"}
Entities[106] = EntityEntry{TRName: "Moth", MCName: "minecraft:butterfly"}
Entities[107] = EntityEntry{TRName: "Possessed Armor", MCName: "minecraft:skeleton"}
Entities[108] = EntityEntry{TRName: "Werewolf", MCName: "minecraft:wolf"}
Entities[109] = EntityEntry{TRName: "Wandering Eye", MCName: "minecraft:phantom"}
Entities[110] = EntityEntry{TRName: "Clown", MCName: "minecraft:witch"}
Entities[111] = EntityEntry{TRName: "Skeleton Sniper", MCName: "minecraft:skeleton"}
Entities[112] = EntityEntry{TRName: "Skeleton Commando", MCName: "minecraft:skeleton"}
Entities[113] = EntityEntry{TRName: "Eye of Cthulhu", MCName: "minecraft:wither_skeleton"}
Entities[114] = EntityEntry{TRName: "Tactical Skeleton", MCName: "minecraft:skeleton"}
Entities[115] = EntityEntry{TRName: "Skeleton Archer", MCName: "minecraft:skeleton"}
Entities[116] = EntityEntry{TRName: "Paladin", MCName: "minecraft:iron_golem"}
Entities[117] = EntityEntry{TRName: "Blue Armored Bones", MCName: "minecraft:wither_skeleton"}
Entities[118] = EntityEntry{TRName: "Necromancer", MCName: "minecraft:witch"}
Entities[119] = EntityEntry{TRName: "Ragged Caster", MCName: "minecraft:witch"}
Entities[120] = EntityEntry{TRName: "Frankenstein", MCName: "minecraft:zombie"}
Entities[121] = EntityEntry{TRName: "Swamp Thing", MCName: "minecraft:wither_skeleton"}
Entities[122] = EntityEntry{TRName: "Vampire", MCName: "minecraft:bat"}
Entities[123] = EntityEntry{TRName: "Butcher", MCName: "minecraft:vindicator"}
Entities[124] = EntityEntry{TRName: "Creature from the Deep", MCName: "minecraft:drowned"}
Entities[125] = EntityEntry{TRName: "Skeletron Head", MCName: "minecraft:wither_skeleton"}
Entities[126] = EntityEntry{TRName: "Plantera", MCName: "minecraft:warden"}
Entities[127] = EntityEntry{TRName: "Golem", MCName: "minecraft:iron_golem"}
Entities[128] = EntityEntry{TRName: "Duke Fishron", MCName: "minecraft:elder_guardian"}
Entities[129] = EntityEntry{TRName: "Empress of Light", MCName: "minecraft:vex"}
Entities[130] = EntityEntry{TRName: "Lunatic Cultist", MCName: "minecraft:witch"}
Entities[131] = EntityEntry{TRName: "Solar Pillar", MCName: "minecraft:end_crystal"}
Entities[132] = EntityEntry{TRName: "Nebula Pillar", MCName: "minecraft:end_crystal"}
Entities[133] = EntityEntry{TRName: "Vortex Pillar", MCName: "minecraft:end_crystal"}
Entities[134] = EntityEntry{TRName: "Stardust Pillar", MCName: "minecraft:end_crystal"}
Entities[135] = EntityEntry{TRName: "Moon Lord", MCName: "minecraft:wither"}
}
