package mapping

func InitItems() {
Items[1]   = ItemEntry{TRName: "Iron Pickaxe", MCName: "minecraft:iron_pickaxe"}
Items[2]   = ItemEntry{TRName: "Dirt Block", MCName: "minecraft:dirt"}
Items[3]   = ItemEntry{TRName: "Stone Block", MCName: "minecraft:stone"}
Items[4]   = ItemEntry{TRName: "Iron Broadsword", MCName: "minecraft:iron_sword"}
Items[5]   = ItemEntry{TRName: "Mushroom", MCName: "minecraft:red_mushroom"}
Items[6]   = ItemEntry{TRName: "Iron Shortsword", MCName: "minecraft:iron_sword"}
Items[7]   = ItemEntry{TRName: "Iron Hammer", MCName: "minecraft:iron_axe"}
Items[8]   = ItemEntry{TRName: "Wood", MCName: "minecraft:oak_log"}
Items[9]   = ItemEntry{TRName: "Wood Platform", MCName: "minecraft:oak_slab"}
Items[10]  = ItemEntry{TRName: "Wood Wall", MCName: "minecraft:oak_planks"}
Items[11]  = ItemEntry{TRName: "Iron Ore", MCName: "minecraft:iron_ore"}
Items[12]  = ItemEntry{TRName: "Copper Ore", MCName: "minecraft:copper_ore"}
Items[13]  = ItemEntry{TRName: "Gold Ore", MCName: "minecraft:gold_ore"}
Items[14]  = ItemEntry{TRName: "Silver Ore", MCName: "minecraft:iron_ore"}
Items[15]  = ItemEntry{TRName: "Copper Watch", MCName: "minecraft:clock"}
Items[16]  = ItemEntry{TRName: "Silver Watch", MCName: "minecraft:clock"}
Items[17]  = ItemEntry{TRName: "Gold Watch", MCName: "minecraft:clock"}
Items[18]  = ItemEntry{TRName: "Depth Meter", MCName: "minecraft:compass"}
Items[19]  = ItemEntry{TRName: "Gold Pickaxe", MCName: "minecraft:golden_pickaxe"}
Items[20]  = ItemEntry{TRName: "Copper Pickaxe", MCName: "minecraft:stone_pickaxe"}
Items[21]  = ItemEntry{TRName: "Silver Pickaxe", MCName: "minecraft:iron_pickaxe"}
Items[22]  = ItemEntry{TRName: "Iron Ingot", MCName: "minecraft:iron_ingot"}
Items[23]  = ItemEntry{TRName: "Copper Ingot", MCName: "minecraft:copper_ingot"}
Items[24]  = ItemEntry{TRName: "Gold Ingot", MCName: "minecraft:gold_ingot"}
Items[25]  = ItemEntry{TRName: "Wooden Sword", MCName: "minecraft:wooden_sword"}
Items[26]  = ItemEntry{TRName: "Wooden Door", MCName: "minecraft:oak_door"}
Items[27]  = ItemEntry{TRName: "Stone Wall", MCName: "minecraft:cobblestone"}
Items[28]  = ItemEntry{TRName: "Acorn", MCName: "minecraft:oak_sapling"}
Items[29]  = ItemEntry{TRName: "Life Crystal", MCName: "minecraft:enchanted_golden_apple"}
Items[30]  = ItemEntry{TRName: "Dirt Wall", MCName: "minecraft:dirt"}
Items[31]  = ItemEntry{TRName: "Bottle", MCName: "minecraft:glass_bottle"}
Items[32]  = ItemEntry{TRName: "Wooden Table", MCName: "minecraft:crafting_table"}
Items[33]  = ItemEntry{TRName: "Wooden Chair", MCName: "minecraft:oak_stairs"}
Items[34]  = ItemEntry{TRName: "Iron Anvil", MCName: "minecraft:anvil"}
Items[35]  = ItemEntry{TRName: "Furnace", MCName: "minecraft:furnace"}
Items[36]  = ItemEntry{TRName: "Work Bench", MCName: "minecraft:crafting_table"}
Items[37]  = ItemEntry{TRName: "Goggles", MCName: "minecraft:leather_helmet"}
Items[38]  = ItemEntry{TRName: "Lens", MCName: "minecraft:spider_eye"}
Items[39]  = ItemEntry{TRName: "Wooden Bow", MCName: "minecraft:bow"}
Items[40]  = ItemEntry{TRName: "Wooden Arrow", MCName: "minecraft:arrow"}
Items[41]  = ItemEntry{TRName: "Flaming Arrow", MCName: "minecraft:spectral_arrow"}
Items[42]  = ItemEntry{TRName: "Shuriken", MCName: "minecraft:snowball"}
Items[43]  = ItemEntry{TRName: "Suspicious Looking Eye", MCName: "minecraft:ender_eye"}
Items[44]  = ItemEntry{TRName: "Demon Bow", MCName: "minecraft:bow"}
Items[45]  = ItemEntry{TRName: "War Axe of the Night", MCName: "minecraft:iron_axe"}
Items[46]  = ItemEntry{TRName: "Light's Bane", MCName: "minecraft:iron_sword"}
Items[47]  = ItemEntry{TRName: "Unholy Arrow", MCName: "minecraft:arrow"}
Items[48]  = ItemEntry{TRName: "Chest", MCName: "minecraft:chest"}
Items[49]  = ItemEntry{TRName: "Band of Regeneration", MCName: "minecraft:golden_apple"}
Items[50]  = ItemEntry{TRName: "Torch", MCName: "minecraft:torch"}
Items[51]  = ItemEntry{TRName: "Glowstick", MCName: "minecraft:glow_ink_sac"}
Items[52]  = ItemEntry{TRName: "Grappling Hook", MCName: "minecraft:fishing_rod"}
Items[53]  = ItemEntry{TRName: "Arrow", MCName: "minecraft:arrow"}
Items[54]  = ItemEntry{TRName: "Musket Ball", MCName: "minecraft:iron_nugget"}
Items[55]  = ItemEntry{TRName: "Musket", MCName: "minecraft:crossbow"}
Items[56]  = ItemEntry{TRName: "Minishark", MCName: "minecraft:crossbow"}
Items[57]  = ItemEntry{TRName: "Silver Ingot", MCName: "minecraft:iron_ingot"}
Items[58]  = ItemEntry{TRName: "Silver Broadsword", MCName: "minecraft:iron_sword"}
Items[59]  = ItemEntry{TRName: "Gold Broadsword", MCName: "minecraft:golden_sword"}
Items[60]  = ItemEntry{TRName: "Vile Mushroom", MCName: "minecraft:brown_mushroom"}
Items[61]  = ItemEntry{TRName: "Vile Powder", MCName: "minecraft:gunpowder"}
Items[62]  = ItemEntry{TRName: "Rotten Chunk", MCName: "minecraft:rotten_flesh"}
Items[63]  = ItemEntry{TRName: "Worm Tooth", MCName: "minecraft:bone_meal"}
Items[64]  = ItemEntry{TRName: "Starfury", MCName: "minecraft:trident"}
Items[65]  = ItemEntry{TRName: "Enchanted Boomerang", MCName: "minecraft:trident"}
Items[66]  = ItemEntry{TRName: "Ice Blade", MCName: "minecraft:diamond_sword"}
Items[67]  = ItemEntry{TRName: "Magic Mirror", MCName: "minecraft:ender_pearl"}
Items[68]  = ItemEntry{TRName: "Hermes Boots", MCName: "minecraft:leather_boots"}
Items[69]  = ItemEntry{TRName: "Cloud in a Bottle", MCName: "minecraft:glass_bottle"}
Items[70]  = ItemEntry{TRName: "Angel Statue", MCName: "minecraft:stone"}
Items[71]  = ItemEntry{TRName: "Copper Coin", MCName: "minecraft:gold_nugget"}
Items[72]  = ItemEntry{TRName: "Silver Coin", MCName: "minecraft:iron_ingot"}
Items[73]  = ItemEntry{TRName: "Gold Coin", MCName: "minecraft:gold_ingot"}
Items[74]  = ItemEntry{TRName: "Platinum Coin", MCName: "minecraft:netherite_scrap"}
Items[75]  = ItemEntry{TRName: "Fallen Star", MCName: "minecraft:nether_star"}
Items[76]  = ItemEntry{TRName: "Sand Block", MCName: "minecraft:sand"}
Items[77]  = ItemEntry{TRName: "Glass", MCName: "minecraft:glass"}
Items[78]  = ItemEntry{TRName: "Cactus", MCName: "minecraft:cactus"}
Items[79]  = ItemEntry{TRName: "Cobalt Ore", MCName: "minecraft:iron_ore"}
Items[80]  = ItemEntry{TRName: "Mythril Ore", MCName: "minecraft:gold_ore"}
Items[81]  = ItemEntry{TRName: "Adamantite Ore", MCName: "minecraft:diamond_ore"}
Items[82]  = ItemEntry{TRName: "Cobalt Bar", MCName: "minecraft:iron_ingot"}
Items[83]  = ItemEntry{TRName: "Mythril Bar", MCName: "minecraft:gold_ingot"}
Items[84]  = ItemEntry{TRName: "Adamantite Bar", MCName: "minecraft:diamond"}
Items[85]  = ItemEntry{TRName: "Wooden Bow", MCName: "minecraft:bow"}
Items[86]  = ItemEntry{TRName: "Bomb", MCName: "minecraft:tnt"}
Items[87]  = ItemEntry{TRName: "Wooden Boomerang", MCName: "minecraft:trident"}
Items[88]  = ItemEntry{TRName: "Wooden Arrow", MCName: "minecraft:arrow"}
Items[89]  = ItemEntry{TRName: "Bomb", MCName: "minecraft:tnt"}
Items[90]  = ItemEntry{TRName: "Dynamite", MCName: "minecraft:tnt"}
Items[91]  = ItemEntry{TRName: "Grenade", MCName: "minecraft:snowball"}
Items[92]  = ItemEntry{TRName: "Magic Missile", MCName: "minecraft:fire_charge"}
Items[93]  = ItemEntry{TRName: "Flower of Fire", MCName: "minecraft:blaze_rod"}
Items[94]  = ItemEntry{TRName: "Water Bolt", MCName: "minecraft:enchanted_book"}
Items[95]  = ItemEntry{TRName: "Gel", MCName: "minecraft:slime_ball"}
Items[96]  = ItemEntry{TRName: "Spear", MCName: "minecraft:trident"}
Items[97]  = ItemEntry{TRName: "Trident", MCName: "minecraft:trident"}
Items[98]  = ItemEntry{TRName: "Rocket Boots", MCName: "minecraft:leather_boots"}
Items[99]  = ItemEntry{TRName: "Flipper", MCName: "minecraft:leather_boots"}
Items[100] = ItemEntry{TRName: "Lesser Healing Potion", MCName: "minecraft:potion"}
Items[101] = ItemEntry{TRName: "Healing Potion", MCName: "minecraft:potion"}
Items[102] = ItemEntry{TRName: "Greater Healing Potion", MCName: "minecraft:potion"}
Items[103] = ItemEntry{TRName: "Mana Potion", MCName: "minecraft:potion"}
Items[104] = ItemEntry{TRName: "Lesser Mana Potion", MCName: "minecraft:potion"}
Items[105] = ItemEntry{TRName: "Greater Mana Potion", MCName: "minecraft:potion"}
Items[106] = ItemEntry{TRName: "Wooden Crate", MCName: "minecraft:barrel"}
Items[107] = ItemEntry{TRName: "Iron Crate", MCName: "minecraft:barrel"}
Items[108] = ItemEntry{TRName: "Golden Crate", MCName: "minecraft:barrel"}
Items[109] = ItemEntry{TRName: "Jungle Spores", MCName: "minecraft:glow_lichen"}
Items[110] = ItemEntry{TRName: "Stinger", MCName: "minecraft:arrow"}
Items[111] = ItemEntry{TRName: "Vine", MCName: "minecraft:vine"}
Items[112] = ItemEntry{TRName: "Bee Keeper", MCName: "minecraft:iron_sword"}
Items[113] = ItemEntry{TRName: "Bee Gun", MCName: "minecraft:crossbow"}
Items[114] = ItemEntry{TRName: "Honey Comb", MCName: "minecraft:honeycomb"}
Items[115] = ItemEntry{TRName: "Bottled Honey", MCName: "minecraft:honey_bottle"}
Items[116] = ItemEntry{TRName: "Hellstone", MCName: "minecraft:netherrack"}
Items[117] = ItemEntry{TRName: "Hellstone Bar", MCName: "minecraft:netherite_scrap"}
Items[118] = ItemEntry{TRName: "Molten Pickaxe", MCName: "minecraft:netherite_pickaxe"}
Items[119] = ItemEntry{TRName: "Molten Fury", MCName: "minecraft:bow"}
Items[120] = ItemEntry{TRName: "Fiery Greatsword", MCName: "minecraft:netherite_sword"}
Items[121] = ItemEntry{TRName: "Phoenix Blaster", MCName: "minecraft:crossbow"}
Items[122] = ItemEntry{TRName: "Sunfury", MCName: "minecraft:diamond_axe"}
Items[123] = ItemEntry{TRName: "Night's Edge", MCName: "minecraft:diamond_sword"}
Items[124] = ItemEntry{TRName: "Dark Lance", MCName: "minecraft:trident"}
Items[125] = ItemEntry{TRName: "Flower of Frost", MCName: "minecraft:blue_ice"}
Items[126] = ItemEntry{TRName: "Frostbrand", MCName: "minecraft:diamond_sword"}
Items[127] = ItemEntry{TRName: "Ice Bow", MCName: "minecraft:bow"}
Items[128] = ItemEntry{TRName: "Frost Armor", MCName: "minecraft:iron_chestplate"}
Items[129] = ItemEntry{TRName: "Excalibur", MCName: "minecraft:diamond_sword"}
Items[130] = ItemEntry{TRName: "Gungnir", MCName: "minecraft:trident"}
Items[131] = ItemEntry{TRName: "Terra Blade", MCName: "minecraft:netherite_sword"}
Items[132] = ItemEntry{TRName: "Bomb", MCName: "minecraft:tnt"}
Items[133] = ItemEntry{TRName: "Megashark", MCName: "minecraft:crossbow"}
Items[134] = ItemEntry{TRName: "Hallowed Armor", MCName: "minecraft:diamond_chestplate"}
Items[135] = ItemEntry{TRName: "Chlorophyte Saber", MCName: "minecraft:emerald_sword"}
Items[136] = ItemEntry{TRName: "Chlorophyte Shotbow", MCName: "minecraft:bow"}
Items[137] = ItemEntry{TRName: "Chlorophyte Armor", MCName: "minecraft:emerald_chestplate"}
Items[138] = ItemEntry{TRName: "Shroomite Armor", MCName: "minecraft:netherite_chestplate"}
Items[139] = ItemEntry{TRName: "Turtle Armor", MCName: "minecraft:turtle_helmet"}
Items[140] = ItemEntry{TRName: "Beetle Armor", MCName: "minecraft:netherite_chestplate"}
Items[141] = ItemEntry{TRName: "Vampire Knives", MCName: "minecraft:iron_sword"}
Items[142] = ItemEntry{TRName: "Scourge of the Corruptor", MCName: "minecraft:trident"}
Items[143] = ItemEntry{TRName: "Paladin's Hammer", MCName: "minecraft:diamond_axe"}
Items[144] = ItemEntry{TRName: "Razorblade Typhoon", MCName: "minecraft:enchanted_book"}
Items[145] = ItemEntry{TRName: "Bubble Gun", MCName: "minecraft:crossbow"}
Items[146] = ItemEntry{TRName: "Rainbow Gun", MCName: "minecraft:crossbow"}
Items[147] = ItemEntry{TRName: "Inferno Fork", MCName: "minecraft:blaze_rod"}
Items[148] = ItemEntry{TRName: "Spectre Staff", MCName: "minecraft:blaze_rod"}
Items[149] = ItemEntry{TRName: "Rod of Discord", MCName: "minecraft:ender_pearl"}
Items[150] = ItemEntry{TRName: "Staff of Earth", MCName: "minecraft:stone_sword"}
Items[151] = ItemEntry{TRName: "Golem Fist", MCName: "minecraft:iron_block"}
Items[152] = ItemEntry{TRName: "Piranha Gun", MCName: "minecraft:crossbow"}
Items[153] = ItemEntry{TRName: "Flairon", MCName: "minecraft:trident"}
Items[154] = ItemEntry{TRName: "Tsunami", MCName: "minecraft:bow"}
Items[155] = ItemEntry{TRName: "Stynger", MCName: "minecraft:crossbow"}
Items[156] = ItemEntry{TRName: "Possessed Hatchet", MCName: "minecraft:diamond_axe"}
Items[157] = ItemEntry{TRName: "The Horseman's Blade", MCName: "minecraft:netherite_sword"}
Items[158] = ItemEntry{TRName: "Stake Launcher", MCName: "minecraft:crossbow"}
Items[159] = ItemEntry{TRName: "Raven Staff", MCName: "minecraft:blaze_rod"}
Items[160] = ItemEntry{TRName: "Betsy's Wrath", MCName: "minecraft:blaze_rod"}
Items[161] = ItemEntry{TRName: "Flying Dragon", MCName: "minecraft:diamond_sword"}
Items[162] = ItemEntry{TRName: "Lunar Flare", MCName: "minecraft:enchanted_book"}
Items[163] = ItemEntry{TRName: "Rainbow Crystal Staff", MCName: "minecraft:amethyst_shard"}
Items[164] = ItemEntry{TRName: "Lunar Portal Staff", MCName: "minecraft:ender_eye"}
Items[165] = ItemEntry{TRName: "Last Prism", MCName: "minecraft:diamond"}
Items[166] = ItemEntry{TRName: "Grappling Hook", MCName: "minecraft:fishing_rod"}
Items[167] = ItemEntry{TRName: "SDMG", MCName: "minecraft:crossbow"}
Items[168] = ItemEntry{TRName: "Celebration", MCName: "minecraft:firework_rocket"}
Items[169] = ItemEntry{TRName: "Zenith", MCName: "minecraft:netherite_sword"}
Items[170] = ItemEntry{TRName: "Copper Shortsword", MCName: "minecraft:stone_sword"}
Items[171] = ItemEntry{TRName: "Tin Ore", MCName: "minecraft:iron_ore"}
Items[172] = ItemEntry{TRName: "Tin Bar", MCName: "minecraft:iron_ingot"}
Items[173] = ItemEntry{TRName: "Lead Ore", MCName: "minecraft:iron_ore"}
Items[174] = ItemEntry{TRName: "Lead Bar", MCName: "minecraft:iron_ingot"}
Items[175] = ItemEntry{TRName: "Tungsten Ore", MCName: "minecraft:gold_ore"}
Items[176] = ItemEntry{TRName: "Tungsten Bar", MCName: "minecraft:gold_ingot"}
Items[177] = ItemEntry{TRName: "Platinum Ore", MCName: "minecraft:diamond_ore"}
Items[178] = ItemEntry{TRName: "Platinum Bar", MCName: "minecraft:diamond"}
Items[179] = ItemEntry{TRName: "Amethyst", MCName: "minecraft:amethyst_shard"}
Items[180] = ItemEntry{TRName: "Topaz", MCName: "minecraft:yellow_dye"}
Items[181] = ItemEntry{TRName: "Sapphire", MCName: "minecraft:blue_dye"}
Items[182] = ItemEntry{TRName: "Emerald", MCName: "minecraft:emerald"}
Items[183] = ItemEntry{TRName: "Ruby", MCName: "minecraft:red_dye"}
Items[184] = ItemEntry{TRName: "Diamond", MCName: "minecraft:diamond"}
Items[185] = ItemEntry{TRName: "Amber", MCName: "minecraft:honeycomb"}
Items[186] = ItemEntry{TRName: "Copper Helmet", MCName: "minecraft:chainmail_helmet"}
Items[187] = ItemEntry{TRName: "Copper Chainmail", MCName: "minecraft:chainmail_chestplate"}
Items[188] = ItemEntry{TRName: "Copper Greaves", MCName: "minecraft:chainmail_leggings"}
Items[189] = ItemEntry{TRName: "Iron Helmet", MCName: "minecraft:iron_helmet"}
Items[190] = ItemEntry{TRName: "Iron Chainmail", MCName: "minecraft:iron_chestplate"}
Items[191] = ItemEntry{TRName: "Iron Greaves", MCName: "minecraft:iron_leggings"}
Items[192] = ItemEntry{TRName: "Silver Helmet", MCName: "minecraft:iron_helmet"}
Items[193] = ItemEntry{TRName: "Silver Chainmail", MCName: "minecraft:iron_chestplate"}
Items[194] = ItemEntry{TRName: "Silver Greaves", MCName: "minecraft:iron_leggings"}
Items[195] = ItemEntry{TRName: "Gold Helmet", MCName: "minecraft:golden_helmet"}
Items[196] = ItemEntry{TRName: "Gold Chainmail", MCName: "minecraft:golden_chestplate"}
Items[197] = ItemEntry{TRName: "Gold Greaves", MCName: "minecraft:golden_leggings"}
Items[198] = ItemEntry{TRName: "Necro Helmet", MCName: "minecraft:skeleton_skull"}
Items[199] = ItemEntry{TRName: "Necro Breastplate", MCName: "minecraft:leather_chestplate"}
Items[200] = ItemEntry{TRName: "Necro Greaves", MCName: "minecraft:leather_leggings"}
Items[201] = ItemEntry{TRName: "Shadow Helmet", MCName: "minecraft:chainmail_helmet"}
Items[202] = ItemEntry{TRName: "Shadow Scalemail", MCName: "minecraft:chainmail_chestplate"}
Items[203] = ItemEntry{TRName: "Shadow Greaves", MCName: "minecraft:chainmail_leggings"}
Items[204] = ItemEntry{TRName: "Jungle Hat", MCName: "minecraft:leather_helmet"}
Items[205] = ItemEntry{TRName: "Jungle Shirt", MCName: "minecraft:leather_chestplate"}
Items[206] = ItemEntry{TRName: "Jungle Pants", MCName: "minecraft:leather_leggings"}
Items[207] = ItemEntry{TRName: "Meteor Helmet", MCName: "minecraft:iron_helmet"}
Items[208] = ItemEntry{TRName: "Meteor Suit", MCName: "minecraft:iron_chestplate"}
Items[209] = ItemEntry{TRName: "Meteor Leggings", MCName: "minecraft:iron_leggings"}
Items[210] = ItemEntry{TRName: "Molten Helmet", MCName: "minecraft:netherite_helmet"}
Items[211] = ItemEntry{TRName: "Molten Breastplate", MCName: "minecraft:netherite_chestplate"}
Items[212] = ItemEntry{TRName: "Molten Greaves", MCName: "minecraft:netherite_leggings"}
Items[213] = ItemEntry{TRName: "Cobalt Helmet", MCName: "minecraft:iron_helmet"}
Items[214] = ItemEntry{TRName: "Cobalt Breastplate", MCName: "minecraft:iron_chestplate"}
Items[215] = ItemEntry{TRName: "Cobalt Leggings", MCName: "minecraft:iron_leggings"}
Items[216] = ItemEntry{TRName: "Mythril Helmet", MCName: "minecraft:golden_helmet"}
Items[217] = ItemEntry{TRName: "Mythril Chainmail", MCName: "minecraft:golden_chestplate"}
Items[218] = ItemEntry{TRName: "Mythril Greaves", MCName: "minecraft:golden_leggings"}
Items[219] = ItemEntry{TRName: "Adamantite Helmet", MCName: "minecraft:diamond_helmet"}
Items[220] = ItemEntry{TRName: "Adamantite Breastplate", MCName: "minecraft:diamond_chestplate"}
Items[221] = ItemEntry{TRName: "Adamantite Leggings", MCName: "minecraft:diamond_leggings"}
Items[222] = ItemEntry{TRName: "Wooden Helmet", MCName: "minecraft:leather_helmet"}
Items[223] = ItemEntry{TRName: "Wooden Breastplate", MCName: "minecraft:leather_chestplate"}
Items[224] = ItemEntry{TRName: "Wooden Greaves", MCName: "minecraft:leather_leggings"}
Items[225] = ItemEntry{TRName: "Rocket Launcher", MCName: "minecraft:crossbow"}
Items[226] = ItemEntry{TRName: "Proximity Mine Launcher", MCName: "minecraft:crossbow"}
Items[227] = ItemEntry{TRName: "Chain Knife", MCName: "minecraft:iron_sword"}
Items[228] = ItemEntry{TRName: "Dao of Pow", MCName: "minecraft:diamond_sword"}
Items[229] = ItemEntry{TRName: "Flower Pow", MCName: "minecraft:diamond_sword"}
Items[230] = ItemEntry{TRName: "Death Sickle", MCName: "minecraft:diamond_sword"}
Items[231] = ItemEntry{TRName: "Mushroom Spear", MCName: "minecraft:trident"}
Items[232] = ItemEntry{TRName: "Nettle Burst", MCName: "minecraft:enchanted_book"}
Items[233] = ItemEntry{TRName: "Wasp Gun", MCName: "minecraft:crossbow"}
Items[234] = ItemEntry{TRName: "Pulse Bow", MCName: "minecraft:bow"}
Items[235] = ItemEntry{TRName: "Snowman Cannon", MCName: "minecraft:crossbow"}
Items[236] = ItemEntry{TRName: "North Pole", MCName: "minecraft:trident"}
Items[237] = ItemEntry{TRName: "Chain Gun", MCName: "minecraft:crossbow"}
Items[238] = ItemEntry{TRName: "Xenopopper", MCName: "minecraft:crossbow"}
Items[239] = ItemEntry{TRName: "Laser Machinegun", MCName: "minecraft:crossbow"}
Items[240] = ItemEntry{TRName: "Electrosphere Launcher", MCName: "minecraft:crossbow"}
Items[241] = ItemEntry{TRName: "Tactical Shotgun", MCName: "minecraft:crossbow"}
Items[242] = ItemEntry{TRName: "Sniper Rifle", MCName: "minecraft:crossbow"}
Items[243] = ItemEntry{TRName: "Seedler", MCName: "minecraft:diamond_sword"}
Items[244] = ItemEntry{TRName: "Bladetongue", MCName: "minecraft:diamond_sword"}
Items[245] = ItemEntry{TRName: "Fetid Baghnakhs", MCName: "minecraft:diamond_sword"}
Items[246] = ItemEntry{TRName: "Toxic Flask", MCName: "minecraft:potion"}
Items[247] = ItemEntry{TRName: "Dart Pistol", MCName: "minecraft:crossbow"}
Items[248] = ItemEntry{TRName: "Dart Rifle", MCName: "minecraft:crossbow"}
Items[249] = ItemEntry{TRName: "Stormbow", MCName: "minecraft:bow"}
Items[250] = ItemEntry{TRName: "Flying Knife", MCName: "minecraft:iron_sword"}
Items[251] = ItemEntry{TRName: "Crystal Serpent", MCName: "minecraft:enchanted_book"}
Items[252] = ItemEntry{TRName: "Sky Fracture", MCName: "minecraft:enchanted_book"}
Items[253] = ItemEntry{TRName: "Onyx Blaster", MCName: "minecraft:crossbow"}
Items[254] = ItemEntry{TRName: "Daedalus Stormbow", MCName: "minecraft:bow"}
Items[255] = ItemEntry{TRName: "Phantom Phoenix", MCName: "minecraft:bow"}
Items[256] = ItemEntry{TRName: "Spirit Flame", MCName: "minecraft:blaze_rod"}
Items[257] = ItemEntry{TRName: "Shadowflame Hex Doll", MCName: "minecraft:enchanted_book"}
Items[258] = ItemEntry{TRName: "Shadowflame Knife", MCName: "minecraft:iron_sword"}
Items[259] = ItemEntry{TRName: "Shadowflame Bow", MCName: "minecraft:bow"}
Items[260] = ItemEntry{TRName: "Blood Thorn", MCName: "minecraft:enchanted_book"}
Items[261] = ItemEntry{TRName: "Durendal", MCName: "minecraft:diamond_sword"}
Items[262] = ItemEntry{TRName: "Morning Star", MCName: "minecraft:diamond_sword"}
Items[263] = ItemEntry{TRName: "Kaleidoscope", MCName: "minecraft:diamond_sword"}
Items[264] = ItemEntry{TRName: "Dark Harvest", MCName: "minecraft:diamond_axe"}
Items[265] = ItemEntry{TRName: "Snapthorn", MCName: "minecraft:vine"}
Items[266] = ItemEntry{TRName: "Spinal Tap", MCName: "minecraft:bone"}
Items[267] = ItemEntry{TRName: "Firecracker", MCName: "minecraft:firework_rocket"}
Items[268] = ItemEntry{TRName: "Cool Whip", MCName: "minecraft:blue_ice"}
Items[269] = ItemEntry{TRName: "Staff of the Frost Hydra", MCName: "minecraft:blaze_rod"}
Items[270] = ItemEntry{TRName: "Queen Spider Staff", MCName: "minecraft:blaze_rod"}
Items[271] = ItemEntry{TRName: "Tempest Staff", MCName: "minecraft:blaze_rod"}
Items[272] = ItemEntry{TRName: "Deadly Sphere Staff", MCName: "minecraft:blaze_rod"}
Items[273] = ItemEntry{TRName: "Xeno Staff", MCName: "minecraft:blaze_rod"}
Items[274] = ItemEntry{TRName: "Optic Staff", MCName: "minecraft:blaze_rod"}
Items[275] = ItemEntry{TRName: "Pirate Staff", MCName: "minecraft:blaze_rod"}
Items[276] = ItemEntry{TRName: "Pygmy Staff", MCName: "minecraft:blaze_rod"}
Items[277] = ItemEntry{TRName: "Slime Staff", MCName: "minecraft:slime_ball"}
Items[278] = ItemEntry{TRName: "Imp Staff", MCName: "minecraft:blaze_rod"}
Items[279] = ItemEntry{TRName: "Hornet Staff", MCName: "minecraft:blaze_rod"}
Items[280] = ItemEntry{TRName: "Spider Staff", MCName: "minecraft:blaze_rod"}
Items[281] = ItemEntry{TRName: "Sanguine Staff", MCName: "minecraft:blaze_rod"}
Items[282] = ItemEntry{TRName: "Blade Staff", MCName: "minecraft:iron_sword"}
Items[283] = ItemEntry{TRName: "Terraprisma", MCName: "minecraft:netherite_sword"}
Items[284] = ItemEntry{TRName: "Finch Staff", MCName: "minecraft:blaze_rod"}
Items[285] = ItemEntry{TRName: "Abigail's Flower", MCName: "minecraft:wither_rose"}
Items[286] = ItemEntry{TRName: "Vampire Frog Staff", MCName: "minecraft:blaze_rod"}
Items[287] = ItemEntry{TRName: "Flinx Staff", MCName: "minecraft:blaze_rod"}
}
