package mapping

func InitTiles() {
Tiles[0]   = TileEntry{TRName: "Air", MCName: "minecraft:air"}
Tiles[1]   = TileEntry{TRName: "Stone Block", MCName: "minecraft:stone"}
Tiles[2]   = TileEntry{TRName: "Dirt Block", MCName: "minecraft:dirt"}
Tiles[3]   = TileEntry{TRName: "Ebonstone Block", MCName: "minecraft:blackstone"}
Tiles[4]   = TileEntry{TRName: "Torch", MCName: "minecraft:torch"}
Tiles[5]   = TileEntry{TRName: "Wood Block", MCName: "minecraft:oak_planks"}
Tiles[6]   = TileEntry{TRName: "Iron Ore", MCName: "minecraft:iron_ore"}
Tiles[7]   = TileEntry{TRName: "Copper Ore", MCName: "minecraft:copper_ore"}
Tiles[8]   = TileEntry{TRName: "Gold Ore", MCName: "minecraft:gold_ore"}
Tiles[9]   = TileEntry{TRName: "Silver Ore", MCName: "minecraft:iron_ore"}
Tiles[10]  = TileEntry{TRName: "Closed Door", MCName: "minecraft:oak_door"}
Tiles[11]  = TileEntry{TRName: "Open Door", MCName: "minecraft:oak_door"}
Tiles[12]  = TileEntry{TRName: "Heart Crystal", MCName: "minecraft:redstone_block"}
Tiles[13]  = TileEntry{TRName: "Bottle", MCName: "minecraft:glass_bottle"}
Tiles[14]  = TileEntry{TRName: "Wooden Table", MCName: "minecraft:crafting_table"}
Tiles[15]  = TileEntry{TRName: "Wooden Chair", MCName: "minecraft:oak_stairs"}
Tiles[16]  = TileEntry{TRName: "Anvil", MCName: "minecraft:anvil"}
Tiles[17]  = TileEntry{TRName: "Furnace", MCName: "minecraft:furnace"}
Tiles[18]  = TileEntry{TRName: "Work Bench", MCName: "minecraft:crafting_table"}
Tiles[19]  = TileEntry{TRName: "Wood Platform", MCName: "minecraft:oak_slab"}
Tiles[20]  = TileEntry{TRName: "Chest", MCName: "minecraft:chest"}
Tiles[21]  = TileEntry{TRName: "Gold Chest", MCName: "minecraft:chest"}
Tiles[22]  = TileEntry{TRName: "Crimstone Block", MCName: "minecraft:red_nether_bricks"}
Tiles[23]  = TileEntry{TRName: "Corrupt Grass", MCName: "minecraft:mycelium"}
Tiles[24]  = TileEntry{TRName: "Sunflower", MCName: "minecraft:sunflower"}
Tiles[25]  = TileEntry{TRName: "Ebonstone Brick", MCName: "minecraft:blackstone"}
Tiles[26]  = TileEntry{TRName: "Wood Wall", MCName: "minecraft:oak_planks"}
Tiles[27]  = TileEntry{TRName: "Grass", MCName: "minecraft:grass_block"}
Tiles[28]  = TileEntry{TRName: "Vines", MCName: "minecraft:vine"}
Tiles[29]  = TileEntry{TRName: "Cobweb", MCName: "minecraft:cobweb"}
Tiles[30]  = TileEntry{TRName: "Wood", MCName: "minecraft:oak_planks"}
Tiles[31]  = TileEntry{TRName: "Mushroom Grass", MCName: "minecraft:mycelium"}
Tiles[32]  = TileEntry{TRName: "Obsidian", MCName: "minecraft:obsidian"}
Tiles[33]  = TileEntry{TRName: "Candle", MCName: "minecraft:torch"}
Tiles[34]  = TileEntry{TRName: "Chandelier", MCName: "minecraft:glowstone"}
Tiles[35]  = TileEntry{TRName: "Ice Block", MCName: "minecraft:ice"}
Tiles[36]  = TileEntry{TRName: "Clay Block", MCName: "minecraft:clay"}
Tiles[37]  = TileEntry{TRName: "Hellforge", MCName: "minecraft:furnace"}
Tiles[38]  = TileEntry{TRName: "Gray Brick", MCName: "minecraft:stone_bricks"}
Tiles[39]  = TileEntry{TRName: "Red Brick", MCName: "minecraft:bricks"}
Tiles[40]  = TileEntry{TRName: "Blue Brick", MCName: "minecraft:blue_concrete"}
Tiles[41]  = TileEntry{TRName: "Green Brick", MCName: "minecraft:green_concrete"}
Tiles[42]  = TileEntry{TRName: "Pink Brick", MCName: "minecraft:pink_concrete"}
Tiles[43]  = TileEntry{TRName: "Gold Brick", MCName: "minecraft:gold_block"}
Tiles[44]  = TileEntry{TRName: "Silver Brick", MCName: "minecraft:iron_block"}
Tiles[45]  = TileEntry{TRName: "Copper Brick", MCName: "minecraft:copper_block"}
Tiles[46]  = TileEntry{TRName: "Spike", MCName: "minecraft:iron_bars"}
Tiles[47]  = TileEntry{TRName: "Water Candle", MCName: "minecraft:torch"}
Tiles[48]  = TileEntry{TRName: "Bookcase", MCName: "minecraft:bookshelf"}
Tiles[49]  = TileEntry{TRName: "Cobweb", MCName: "minecraft:cobweb"}
Tiles[50]  = TileEntry{TRName: "Vines", MCName: "minecraft:vine"}
Tiles[51]  = TileEntry{TRName: "Sand Block", MCName: "minecraft:sand"}
Tiles[52]  = TileEntry{TRName: "Glass", MCName: "minecraft:glass"}
Tiles[53]  = TileEntry{TRName: "Sandstone", MCName: "minecraft:sandstone"}
Tiles[54]  = TileEntry{TRName: "Sand Block", MCName: "minecraft:sand"}
Tiles[55]  = TileEntry{TRName: "Obsidian Brick", MCName: "minecraft:obsidian"}
Tiles[56]  = TileEntry{TRName: "Obsidian Brick", MCName: "minecraft:obsidian"}
Tiles[57]  = TileEntry{TRName: "Hellstone", MCName: "minecraft:netherrack"}
Tiles[58]  = TileEntry{TRName: "Ash Block", MCName: "minecraft:gray_concrete_powder"}
Tiles[59]  = TileEntry{TRName: "Mud Block", MCName: "minecraft:mud"}
Tiles[60]  = TileEntry{TRName: "Mud Block", MCName: "minecraft:mud"}
Tiles[61]  = TileEntry{TRName: "Jungle Grass", MCName: "minecraft:moss_block"}
Tiles[62]  = TileEntry{TRName: "Jungle Spores", MCName: "minecraft:glow_lichen"}
Tiles[63]  = TileEntry{TRName: "Mushroom", MCName: "minecraft:red_mushroom"}
Tiles[64]  = TileEntry{TRName: "Glowing Mushroom", MCName: "minecraft:shroomlight"}
Tiles[65]  = TileEntry{TRName: "Demon Altar", MCName: "minecraft:enchanting_table"}
Tiles[66]  = TileEntry{TRName: "Potted Plant", MCName: "minecraft:flower_pot"}
Tiles[67]  = TileEntry{TRName: "Pink Gel", MCName: "minecraft:pink_wool"}
Tiles[68]  = TileEntry{TRName: "Crystal Shard", MCName: "minecraft:amethyst_block"}
Tiles[69]  = TileEntry{TRName: "Meteorite", MCName: "minecraft:magma_block"}
Tiles[70]  = TileEntry{TRName: "Meteorite", MCName: "minecraft:magma_block"}
Tiles[71]  = TileEntry{TRName: "Silt Block", MCName: "minecraft:light_gray_concrete_powder"}
Tiles[72]  = TileEntry{TRName: "Pearlsand Block", MCName: "minecraft:white_concrete_powder"}
Tiles[73]  = TileEntry{TRName: "Crystal Block", MCName: "minecraft:amethyst_block"}
Tiles[74]  = TileEntry{TRName: "Stone Slab", MCName: "minecraft:smooth_stone"}
Tiles[75]  = TileEntry{TRName: "Sandstone Slab", MCName: "minecraft:sandstone"}
Tiles[76]  = TileEntry{TRName: "Lihzahrd Brick", MCName: "minecraft:terracotta"}
Tiles[77]  = TileEntry{TRName: "Blue Slab", MCName: "minecraft:blue_concrete"}
Tiles[78]  = TileEntry{TRName: "Red Slab", MCName: "minecraft:red_concrete"}
Tiles[79]  = TileEntry{TRName: "Green Slab", MCName: "minecraft:green_concrete"}
Tiles[80]  = TileEntry{TRName: "Pink Slab", MCName: "minecraft:pink_concrete"}
Tiles[81]  = TileEntry{TRName: "Cactus", MCName: "minecraft:cactus"}
Tiles[82]  = TileEntry{TRName: "Cloud", MCName: "minecraft:white_wool"}
Tiles[83]  = TileEntry{TRName: "Rain Cloud", MCName: "minecraft:gray_wool"}
Tiles[84]  = TileEntry{TRName: "Bee Hive", MCName: "minecraft:bee_nest"}
Tiles[85]  = TileEntry{TRName: "Honey Block", MCName: "minecraft:honey_block"}
Tiles[86]  = TileEntry{TRName: "Crispy Honey Block", MCName: "minecraft:honeycomb_block"}
Tiles[87]  = TileEntry{TRName: "Lava Moss", MCName: "minecraft:glow_lichen"}
Tiles[88]  = TileEntry{TRName: "Pumpkin", MCName: "minecraft:pumpkin"}
Tiles[89]  = TileEntry{TRName: "Gel", MCName: "minecraft:slime_block"}
Tiles[90]  = TileEntry{TRName: "Frozen Chest", MCName: "minecraft:chest"}
Tiles[91]  = TileEntry{TRName: "Bone Block", MCName: "minecraft:bone_block"}
Tiles[92]  = TileEntry{TRName: "Coral", MCName: "minecraft:tube_coral"}
Tiles[93]  = TileEntry{TRName: "Pink Prickly Pear", MCName: "minecraft:pink_tulip"}
Tiles[94]  = TileEntry{TRName: "Planter Box", MCName: "minecraft:composter"}
Tiles[95]  = TileEntry{TRName: "Logic Gate", MCName: "minecraft:repeater"}
Tiles[96]  = TileEntry{TRName: "Stone Door", MCName: "minecraft:iron_door"}
Tiles[97]  = TileEntry{TRName: "Trash Can", MCName: "minecraft:cauldron"}
Tiles[98]  = TileEntry{TRName: "Barrel", MCName: "minecraft:barrel"}
Tiles[99]  = TileEntry{TRName: "Safe", MCName: "minecraft:iron_block"}
Tiles[100] = TileEntry{TRName: "Chlorophyte Ore", MCName: "minecraft:emerald_ore"}
Tiles[101] = TileEntry{TRName: "Teal Mushroom", MCName: "minecraft:warped_fungus"}
Tiles[102] = TileEntry{TRName: "Minecart Track", MCName: "minecraft:rail"}
Tiles[103] = TileEntry{TRName: "Bubble", MCName: "minecraft:glass"}
Tiles[104] = TileEntry{TRName: "Pressure Plate", MCName: "minecraft:stone_pressure_plate"}
Tiles[105] = TileEntry{TRName: "Lizard Brick", MCName: "minecraft:terracotta"}
Tiles[106] = TileEntry{TRName: "Living Wood", MCName: "minecraft:oak_wood"}
Tiles[107] = TileEntry{TRName: "Snow Block", MCName: "minecraft:snow_block"}
Tiles[108] = TileEntry{TRName: "Snow Brick", MCName: "minecraft:snow_block"}
Tiles[109] = TileEntry{TRName: "Ice Block", MCName: "minecraft:ice"}
Tiles[110] = TileEntry{TRName: "Thin Ice", MCName: "minecraft:frosted_ice"}
Tiles[111] = TileEntry{TRName: "Palladium Ore", MCName: "minecraft:iron_ore"}
Tiles[112] = TileEntry{TRName: "Orichalcum Ore", MCName: "minecraft:gold_ore"}
Tiles[113] = TileEntry{TRName: "Titanium Ore", MCName: "minecraft:diamond_ore"}
Tiles[114] = TileEntry{TRName: "Adamantite Ore", MCName: "minecraft:netherite_block"}
Tiles[115] = TileEntry{TRName: "Mythril Ore", MCName: "minecraft:gold_ore"}
Tiles[116] = TileEntry{TRName: "Cobalt Ore", MCName: "minecraft:iron_ore"}
Tiles[117] = TileEntry{TRName: "Hallowed Grass", MCName: "minecraft:grass_block"}
Tiles[118] = TileEntry{TRName: "Pearlsand Block", MCName: "minecraft:white_concrete_powder"}
Tiles[119] = TileEntry{TRName: "Pearlstone Brick", MCName: "minecraft:white_concrete"}
Tiles[120] = TileEntry{TRName: "Iridescent Brick", MCName: "minecraft:white_concrete"}
Tiles[121] = TileEntry{TRName: "Granite Block", MCName: "minecraft:granite"}
Tiles[122] = TileEntry{TRName: "Marble Block", MCName: "minecraft:quartz_block"}
Tiles[123] = TileEntry{TRName: "Martian Conduit", MCName: "minecraft:copper_block"}
Tiles[124] = TileEntry{TRName: "Cog", MCName: "minecraft:observer"}
Tiles[125] = TileEntry{TRName: "Diamond Gemspark", MCName: "minecraft:sea_lantern"}
Tiles[126] = TileEntry{TRName: "Amber Gemspark", MCName: "minecraft:glowstone"}
Tiles[127] = TileEntry{TRName: "Ruby Gemspark", MCName: "minecraft:redstone_lamp"}
Tiles[128] = TileEntry{TRName: "Emerald Gemspark", MCName: "minecraft:green_wool"}
Tiles[129] = TileEntry{TRName: "Sapphire Gemspark", MCName: "minecraft:blue_wool"}
Tiles[130] = TileEntry{TRName: "Topaz Gemspark", MCName: "minecraft:yellow_wool"}
Tiles[131] = TileEntry{TRName: "Amethyst Gemspark", MCName: "minecraft:purple_wool"}
Tiles[132] = TileEntry{TRName: "Slime Block", MCName: "minecraft:slime_block"}
Tiles[133] = TileEntry{TRName: "Frozen Slime Block", MCName: "minecraft:blue_ice"}
Tiles[134] = TileEntry{TRName: "Asphalt Block", MCName: "minecraft:black_concrete"}
Tiles[135] = TileEntry{TRName: "Pink Slime Block", MCName: "minecraft:pink_wool"}
Tiles[136] = TileEntry{TRName: "Living Fire", MCName: "minecraft:fire"}
Tiles[137] = TileEntry{TRName: "Echo Block", MCName: "minecraft:gray_stained_glass"}
Tiles[138] = TileEntry{TRName: "Moss", MCName: "minecraft:moss_block"}
Tiles[139] = TileEntry{TRName: "Grate", MCName: "minecraft:iron_bars"}
Tiles[140] = TileEntry{TRName: "Reef Block", MCName: "minecraft:brain_coral_block"}
Tiles[141] = TileEntry{TRName: "Large Bamboo", MCName: "minecraft:bamboo_block"}
Tiles[142] = TileEntry{TRName: "Bamboo", MCName: "minecraft:bamboo"}

Walls[1]   = TileEntry{TRName: "Stone Wall", MCName: "minecraft:cobblestone"}
Walls[2]   = TileEntry{TRName: "Dirt Wall", MCName: "minecraft:dirt"}
Walls[3]   = TileEntry{TRName: "Ebonstone Wall", MCName: "minecraft:blackstone"}
Walls[4]   = TileEntry{TRName: "Wood Wall", MCName: "minecraft:oak_planks"}
Walls[5]   = TileEntry{TRName: "Gray Brick Wall", MCName: "minecraft:stone_bricks"}
Walls[6]   = TileEntry{TRName: "Red Brick Wall", MCName: "minecraft:bricks"}
Walls[7]   = TileEntry{TRName: "Blue Brick Wall", MCName: "minecraft:blue_concrete"}
Walls[8]   = TileEntry{TRName: "Green Brick Wall", MCName: "minecraft:green_concrete"}
Walls[9]   = TileEntry{TRName: "Pink Brick Wall", MCName: "minecraft:pink_concrete"}
Walls[10]  = TileEntry{TRName: "Gold Brick Wall", MCName: "minecraft:gold_block"}
Walls[11]  = TileEntry{TRName: "Silver Brick Wall", MCName: "minecraft:iron_block"}
Walls[12]  = TileEntry{TRName: "Copper Brick Wall", MCName: "minecraft:copper_block"}
Walls[13]  = TileEntry{TRName: "Hellstone Brick Wall", MCName: "minecraft:nether_bricks"}
Walls[14]  = TileEntry{TRName: "Obsidian Brick Wall", MCName: "minecraft:obsidian"}
Walls[15]  = TileEntry{TRName: "Glass Wall", MCName: "minecraft:glass"}
Walls[16]  = TileEntry{TRName: "Pearlstone Wall", MCName: "minecraft:white_concrete"}
Walls[17]  = TileEntry{TRName: "Crimstone Wall", MCName: "minecraft:red_nether_bricks"}
Walls[18]  = TileEntry{TRName: "Planked Wall", MCName: "minecraft:oak_planks"}
Walls[19]  = TileEntry{TRName: "Living Wood Wall", MCName: "minecraft:oak_wood"}
Walls[20]  = TileEntry{TRName: "Disc Wall", MCName: "minecraft:spruce_planks"}
Walls[21]  = TileEntry{TRName: "Pearlstone Wall", MCName: "minecraft:white_concrete"}
Walls[22]  = TileEntry{TRName: "Candy Cane Wall", MCName: "minecraft:red_wool"}
Walls[23]  = TileEntry{TRName: "Green Candy Cane Wall", MCName: "minecraft:green_wool"}
Walls[24]  = TileEntry{TRName: "Snow Wall", MCName: "minecraft:snow_block"}
Walls[25]  = TileEntry{TRName: "Ice Wall", MCName: "minecraft:ice"}
Walls[26]  = TileEntry{TRName: "Bone Wall", MCName: "minecraft:bone_block"}
Walls[27]  = TileEntry{TRName: "Spider Wall", MCName: "minecraft:cobweb"}
Walls[28]  = TileEntry{TRName: "Mud Wall", MCName: "minecraft:mud"}
Walls[29]  = TileEntry{TRName: "Cloud Wall", MCName: "minecraft:white_wool"}
Walls[30]  = TileEntry{TRName: "Hive Wall", MCName: "minecraft:honeycomb_block"}
Walls[31]  = TileEntry{TRName: "Lihzahrd Wall", MCName: "minecraft:terracotta"}
Walls[32]  = TileEntry{TRName: "Sandstone Wall", MCName: "minecraft:sandstone"}
Walls[33]  = TileEntry{TRName: "Granite Wall", MCName: "minecraft:granite"}
Walls[34]  = TileEntry{TRName: "Marble Wall", MCName: "minecraft:quartz_block"}
Walls[35]  = TileEntry{TRName: "Crystal Wall", MCName: "minecraft:amethyst_block"}
Walls[36]  = TileEntry{TRName: "Chlorophyte Wall", MCName: "minecraft:emerald_block"}
Walls[37]  = TileEntry{TRName: "Bamboo Wall", MCName: "minecraft:bamboo_block"}
}
